[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colours = "0.1.1"
rayon = "1.7.0"
sdl2 = "0.35.2"
